if (GetLocale() == "deDE") then
	MPOWA_MAINFRAME_HEAD = "Modified Power Auras"

	MPOWA_BUTTON_EDIT = "Aura bearbeiten"
	MPOWA_BUTTON_ADD = "Aura hinzufügen"
	MPOWA_BUTTON_REMOVE = "Aure entfernen"
	MPOWA_BUTTON_PROFILE = "Profile"
	MPOWA_BUTTON_CLOSE = "Schließen"
	MPOWA_BUTTON_TEST = "Test"
	MPOWA_BUTTON_TESTALL = "Alles testen"
	MPOWA_BUTTON_IMPORT = "Importieren"
	MPOWA_BUTTON_SAVE = "Speichern"
	MPOWA_BUTTON_REMOVE = "Entfernen"
	MPOWA_BUTTON_CANCEL = "Abbrechen"
	MPOWA_BUTTON_OKAY = "Okay"

	MPOWA_CONFIGFRAME_NAME = "Configurations-Frame"
	MPOWA_CONFIGFRAME_EFFECT_EDITOR = "Effekt"
	MPOWA_CONFIGFRAME_TIMER_EDITOR = "Timer"
	MPOWA_CONFIGFRAME_SOUND_EDITOR = "Ton"
	MPOWA_CONFIGFRAME_ABOUT = "Über MPOWA"
	MPOWA_PROFILEFRAME_NAME = "Profil-Editor"
	MPOWA_ICONFRAME_NAME = "Icon-Frame"

	MPOWA_SLIDER_OPACITY = "Deckkraft:"
	MPOWA_SLIDER_OPACITY_TOOLTIP = "Bewege das, um die Deckkraft zu ändern."
	MPOWA_SLIDER_POSX = "Position X:"
	MPOWA_SLIDER_POSX_TOOLTIP = "Bewege das, um die horizontale Position zu ändern."
	MPOWA_SLIDER_POSY = "Position Y:"
	MPOWA_SLIDER_POSY_TOOLTIP = "Bewege das, um die vertikale Position zu ändern."
	MPOWA_SLIDER_SIZE = "Skalierung:"
	MPOWA_SLIDER_SIZE_TOOLTIP = "Bewege das, um die Größe zu ändern."
	MPOWA_SLIDER_BEGINSOUND = "Tondatei: "
	MPOWA_SLIDER_BEGINSOUND_TOOLTIP = "Bewege das, um den Ton zu ändern, wenn eine Aura hinzugefügt wird."
	MPOWA_SLIDER_ENDSOUND = "Tondatei: "
	MPOWA_SLIDER_ENDSOUND_TOOLTIP = "Bewege das, um den Ton zu ändern, wenn eine Aura verschwindet."

	MPOWA_EDITBOX_TOOLTIP = "Schreibe hier den genauen Auranamen hinein, womit das Icon aufgerufen wird. Das Icon wird für Spielerauras automatisch gefunden."
	MPOWA_EDITBOX_NAME = "Genauer name der Aura:"
	MPOWA_EDITBOX_STACKS_NAME = "Aufladungen:"
	MPOWA_EDITBOX_STACKS_TOOLTIP = "Schreibe hier die Anzahl der Aufladungen rein, um die Aura aufzurufen oder verschwinden zu lassen. Folgende Operatoren sind zulässig: '<5' '>3' '=11' '!5' '>=0' '<=6' '2-8'"
	MPOWA_EDITBOX_DEBUFFDURATION = "Dauer:"
	MPOWA_EDITBOX_DEBUFFDURATION_TOOLTIP = "Schreibe hier die Dauer der Aura des Ziels hinein."
	MPOWA_EDITBOX_FLASHANIM = "Start:"
	MPOWA_EDITBOX_FLASHANIM_TOOLTIP = "Schreibe hier die Dauer rein, wenn es anfangen soll zu blinken."

	MPOWA_CHECKBUTTON_DEBUFF = "Ist Debuff"
	MPOWA_CHECKBUTTON_DEBUFF_TOOLTIP = "Kreuze das an, wenn die Aura ein Debuff ist."
	MPOWA_CHECKBUTTON_SHOWIFNOTACTIVE = "Invertieren"
	MPOWA_CHECKBUTTON_SHOWIFNOTACTIVE_TOOLTIP = "Kreuze das an, um das erscheinen der Aura zu invertieren. Es wird also gezeigt, wenn es NICHT aktiv ist."
	MPOWA_CHECKBUTTON_TIMER = "Timer"
	MPOWA_CHECKBUTTON_TIMER_TOOLTIP = "Kreuze das an, um den Timer zu aktivieren."
	MPOWA_CHECKBUTTON_SHOWCOOLDOWN = "Wenn Cooldown"
	MPOWA_CHECKBUTTON_SHOWCOOLDOWN_TOOLTIP = "Kreuze das an, um die Aura zu zeigen, wenn die Fähigkeit auf cooldown ist."
	MPOWA_CHECKBUTTON_ENEMYTARGET = "|cFFFF8080Gegnerisches Ziel|r"
	MPOWA_CHECKBUTTON_ENEMYTARGET_TOOLTIP = "Kreuze das an, um das gegnerische Ziel zu nutzen, anstatt dir. Notiz: Der Timer wird damit ungenau."
	MPOWA_CHECKBUTTON_INCOMBAT = "Im Kampf"
	MPOWA_CHECKBUTTON_INCOMBAT_TOOLTIP = "Kreuze das an, um einzustellen, wann die Aura gezeigt wird. Nichts => Ignoriere Kampfstatus, Angekreuzt => Zeige es, wenn du im Kampf bist, Kreuz => Zeige es, wenn du NICHT im Kampf bist."
	MPOWA_CHECKBUTTON_INPARTY = "In Gruppe"
	MPOWA_CHECKBUTTON_INPARTY_TOOLTIP = "Kreuze das an, um einzustellen, wann die Aura gezeigt wird. Nichts => Ignoriere Gruppenstatus, Angekreuzt => Zeige es, wenn du in einer Gruppe bist, Kreuz => Zeige es, wenn du NICHT in einer Gruppe bist."
	MPOWA_CHECKBUTTON_INRAID = "Im Schlachtzug"
	MPOWA_CHECKBUTTON_INRAID_TOOLTIP = "Kreuze das an, um einzustellen, wann die Aura gezeigt wird. Nichts => Ignoriere Schlachtzugstatus, Angekreuzt => Zeige es, wenn du im Schlachtzug bist, Kreuz => Zeige es, wenn du NICHT im Schlachtzug bist."
	MPOWA_CHECKBUTTON_ALIVE = "Ist am leben"
	MPOWA_CHECKBUTTON_ALIVE_TOOLTIP = "Kreuze das an, um einzustellen, wann die Aura gezeigt wird. Nichts => Ignoriere status, Angekreuzt => Zeige es, wenn du lebst, Kreuz => Zeige es, wenn du NICHT lebst."
	MPOWA_CHECKBUTTON_MOUNTED = "Ist aufgesattelt"
	MPOWA_CHECKBUTTON_MOUNTED_TOOLTIP = "Kreuze das an, um einzustellen, wann die Aura gezeigt wird. Nichts => Ignoriere status, Angekreuzt => Zeige es, wenn du aufgesattelt bist, Kreuz => Zeige es, wenn du NICHT aufgesattelt bist."
	MPOWA_CHECKBUTTON_FRIENDLYTARGET = "|cFF66CD00Freundliches Ziel|r"
	MPOWA_CHECKBUTTON_FRIENDLYTARGET_TOOLTIP = "Kreuze das an, um das freundliche Ziel zu nutzen, anstatt dir. Notiz: Der Timer wird damit ungenau."
	MPOWA_CHECKBUTTON_ISBATTLEGROUND = "Im Schlachtfeld"
	MPOWA_CHECKBUTTON_ISBATTLEGROUND_TOOLTIP = "Kreuze das an, um einzustellen, wann die Aura gezeigt wird. Nichts => Ignoriere status, Angekreuzt => Zeige es, wenn du im Schlachtfeld bist, Kreuz => Zeige es, wenn du NICHT im Schlachtfeld bist."
	MPOWA_CHECKBUTTON_HUNDREDS = "Zeige hundertstel"
	MPOWA_CHECKBUTTON_HUNDREDS_TOOLTIP = "Kreuze das an, um hundertstel anzeigen zu lassen."
	MPOWA_CHECKBUTTON_COLOR = "Eigene Farbe: "
	MPOWA_CHECKBUTTON_COLOR_TOOLTIP = "Kreuze das an, um deine eigene Farbe zu nutzen, anstatt weiß."
	MPOWA_CHECKBUTTON_BEGINSOUND = "Spiele Ton, wenn eine Aura erscheint"
	MPOWA_CHECKBUTTON_BEGINSOUND_TOOLTIP = "Kreuze das an, um einen Ton abzuspielen, wenn eine Aura erscheint."
	MPOWA_CHECKBUTTON_ENDSOUND = "Spiele Ton, wenn eine Aura verschwindet"
	MPOWA_CHECKBUTTON_ENDSOUND_TOOLTIP = "Kreuze das an, um einen Ton abzuspielen, wenn eine Aura verschwindet."
	MPOWA_CHECKBUTTON_RAIDMEMBER = "|cFF66CD00Schlachtzug/Gruppenmitglied|r"
	MPOWA_CHECKBUTTON_RAIDMEMBER_TOOLTIP = "Kreuze das an, um einen Schlachtzugs- oder Gruppenmitglied zu suchen."
	MPOWA_CHECKBUTTON_EXACTNAME = "Genauer Name"
	MPOWA_CHECKBUTTON_EXACTNAME_TOOLTIP = "Nutze den exakten Namen anstatt einen groben filter."
	MPOWA_CHECKBUTTON_FLASHANIM = "Flash Animation"
	MPOWA_CHECKBUTTON_FLASHANIM_TOOLTIP = "Kreuze das an, um die Blinkanimation zu aktivieren."
	MPOWA_CHECKBUTTON_SECS_LEFT = "Wenn X sek. über"
	MPOWA_CHECKBUTTON_SECS_LEFT_TOOLTIP = "Zeige es, wenn X Sekunden verbleiben, bis der cooldown abläuft oder die aura verschwindet."
	MPOWA_CHECKBUTTON_ININSTANCE = "In Raid-Instanz"
	MPOWA_CHECKBUTTON_ININSTANCE_TOOLTIP = "Kreuze das an, um einzustellen, wann die Aura gezeigt wird. Nichts => Ignoriere status, Angekreuzt => Zeige es, wenn du in einer Raid-Instanz bist, Kreuz => Zeige es, wenn du NICHT in einer Raid-Instanz bist."
	MPOWA_EDITBOX_SECONDS = "Sekunden:"
	MPOWA_EDITBOX_SECONDS_TOOLTIP = "Wieviele Sekunden, bis die Aura gezeigt wird."

	MPOWA_SCRIPT_MOUNT_100 = "Erhöht das Bewegungstempo um 100"
	MPOWA_SCRIPT_MOUNT_60 = "Erhöht das Bewegungstempo um 60"

	MPOWA_TEXT_ABOUT_MPOWA = "Modified Power Auras ist die erweiterte Version von Power Auras. Es verfügt über eine vielzahl von Funktionen, die erst mit späteren Versionen hinzukomen. Zusätzlich verfügt es über eigene Funktion, die das AddOn einmalig machen."
	MPOWA_TEXT_CREATOR_TITLE = "Wer hat Modified Power Auras erstellt?"
	MPOWA_TEXT_CREATOR = "VCB wurde von Shino (Albea) <Synced> entwickelt, der auf Kronos (Twinstar.cz) gearbeitet hat. In der Twinstar-Community ist er als Geigerkind bekannt."
	MPOWA_TEXT_SPECIALTHANKS_TITLE = "Speziellen dank an "
	MPOWA_TEXT_SPECIALTHANKS = "Sinesther - Es ist seine AddOn Idee, bloß wurde es nun für Vanilla stark verbessert. \nmartinjlowm - Entwickler der Library AnimationGroup"
	MPOWA_TEXT_SUPPORTING_TITLE = "Danke für das unterstützen!"
	MPOWA_TEXT_SUPPORTING = "Noch keiner"
	
	MPOWA_CHECKBUTTON_FADEIN = "Fade in"
	MPOWA_CHECKBUTTON_FADEIN_TOOLTIP = "Kreuze das an, um eine Flashanimation zu haben, wenn die Aura erscheint."
	MPOWA_CHECKBUTTON_FADEOUT = "Fade out"
	MPOWA_CHECKBUTTON_FADEOUT_TOOLTIP = "Kreuze das an, um eine Flashanimation zu haben, wenn die Aura verschwindet."
	MPOWA_CHECKBUTTON_GROWOUT = "Grow out"
	MPOWA_CHECKBUTTON_GROWOUT_TOOLTIP = "Kreuze das an, um eine Growout-Animation zu haben, wenn die Aura verschwindet."
	MPOWA_EDITBOX_PLAYER_NAME = "Spielername:"
	MPOWA_EDITBOX_PLAYER_NAME_TOOLTIP = "Füge den Namen, des Raid/Gruppenmitglieds ein."
	
	MPOWA_AURA_GONE_SELF = "(.+) schwindet von euch%."
	MPOWA_AURA_GONE_OTHER = "(.+) schwindet von (.+)%."
	
	MPOWA_ZONES_MC = "Geschmolzener Kern"
	MPOWA_ZONES_BWL = "Pechschwingenhort"
	MPOWA_ZONES_ONY = "Onyxias Hort"
	MPOWA_ZONES_ZG = "Zul'Gurub"
	MPOWA_ZONES_AQ401 = "Ahn'Qiraj"
	MPOWA_ZONES_AQ402 = "Tempel von Ahn'Qiraj"
	MPOWA_ZONES_AQ20 = "Ruinen von Ahn'Qiraj"
	MPOWA_ZONES_NAXX = "Naxxramas"

	MPOWA_CHECKBUTTON_HIDE_STACKS_TOOLTIP = "Kreuze das an, um die Anzahl zu verstecken"
	MPOWA_CHECKBUTTON_HIDE_STACKS = "Verstecke Anzahl"
	MPOWA_CHECKBUTTON_USE_DESCRIPTION_TOOLTIP = "Kreuze das an, um die Auratextur als zweiten Indikator für die Erkennung zu verwenden."
	MPOWA_CHECKBUTTON_USE_DESCRIPTION = "Nutze Textur"
	MPOWA_EDITBOX_SecondSpecifier_TOOLTIP = "Schreibe hier den genauen Texturnamen der aura hinein."
	MPOWA_EDITBOX_SecondSpecifier = "Exakter Texturname:"
	
	MPOWA_WINDFURY_GAIN = "Ihr bekommt 'Totem des Windzorns'."
	MPOWA_WINDFURY_GAIN2 = "Ihr bekommt 'Waffe des Windzorns'."
	MPOWA_WINDFURY_GAIN3 = "Ihr bekommt 'Windfury'."
	MPOWA_WINDFURY_GONE = "'Totem des Windzorns' schwindet von Euch."
	MPOWA_WINDFURY_GONE2 = "'Waffe des Windzorns' schwindet von Euch."
	MPOWA_WINDFURY_GONE3 = "'Windfury' schwindet von Euch."
	
	MPOWA_ONSTART = "Erscheint"
	MPOWA_ONFINISHED = "Verschwindet"
	MPOWA_CHECKBUTTON_GROWIN_TOOLTIP = "Kreuze das an, um eine Einwachsen-Animation zu bekommen, wenn die Aura erscheint."
	MPOWA_CHECKBUTTON_GROWIN = "Einwachsen"
	MPOWA_CHECKBUTTON_ROTATE_TOOLTIP = "Kreuze das an, um eine Rotierungs-Animation zu bekommen, wenn die Aura erscheint oder verschwindet."
	MPOWA_CHECKBUTTON_ROTATEIN = "Eindrehen"
	MPOWA_CHECKBUTTON_ROTATEOUT = "Ausdrehen"
	MPOWA_CHECKBUTTON_SIZEIN_TOOLTIP = "Kreuze das an, um eine SizeIn-Animation zu bekommen, wenn die Aura erscheint."
	MPOWA_CHECKBUTTON_SIZEIN = "Size in"
	MPOWA_CHECKBUTTON_TRANSLATE_TOOLTIP = "Kreuze das an, um eine Verschiebe-Animation zu bekommen, wenn die Aura verschwindet."
	MPOWA_CHECKBUTTON_TRANSLATE = "Verschieben"
	MPOWA_CHECKBUTTON_ESCAPE_TOOLTIP = "Kreuze das an, um eine Flucht-Animation zu bekommen, wenn die Aura erscheint oder verschwindet."
	MPOWA_CHECKBUTTON_ESCAPEIN = "Einbrechen"
	MPOWA_CHECKBUTTON_ESCAPEOUT = "Ausbrechen"
	MPOWA_CHECKBUTTON_BATMAN_TOOLTIP = "Kreuze das an, um eine Batman-Animation zu bekommen, wenn die Aura erscheint oder verschwindet."
	MPOWA_CHECKBUTTON_BATMANIN = "Batman ein"
	MPOWA_CHECKBUTTON_BATMANOUT = "Batman aus"
	MPOWA_CHECKBUTTON_SHRINK_TOOLTIP = "Kreuze das an, um eine Schrumpf-Animation zu bekommen, wenn die Aura verschwindet."
	MPOWA_CHECKBUTTON_SHRINK = "Schrumpfen"
	MPOWA_SLIDER_ANIMDURATION_TOOLTIP = "Verschiebe das, um die Dauer der Animation zu verändern."
	MPOWA_SLIDER_ANIMDURATION = "Animationsdauer"
	MPOWA_SLIDER_TRANSLATE_TOOLTIP = "Verschiebe das, um den jeweiligen Verschiebepararmeter zu verändern."
	MPOWA_SLIDER_TRANSLATEX = "Verschiebe X"
	MPOWA_SLIDER_TRANSLATEY = "Verschiebe Y"
	MPOWA_SLIDER_FADEALPHA_TOOLTIP = "Verschiebe das, um die Veränderung der Transperenz der Animation zu verändern."
	MPOWA_SLIDER_FADEALPHA = "Verschwinde"
	MPOWA_SLIDER_SCALEFACTOR_TOOLTIP = "Verschiebe das, um den Skalierungsfaktor der Animation zu verändern."
	MPOWA_SLIDER_SCALEFACTOR = "Skalierungsfaktor"
	
	MPOWA_CHECKBUTTON_ISDYNAMICGROUP_TOOLTIP = "Kreuze das an, um diese Aura als dynamische Gruppe zu definieren. Du kannst andere Auren hinzufügen, indem du rechts in das Feld die Nummer der Gruppenaura einträgst."
	MPOWA_CHECKBUTTON_ISDYNAMICGROUP = "Ist dynamische Gruppe"
	MPOWA_EDITBOX_GROUPNUMBER_TOOLTIP = "Trage die Nummer der dynamischen Gruppe ein, um diese Aura hinzufügen."
	MPOWA_EDITBOX_GROUPNUMBER = "Gruppenummer"
	
	MPOWA_EDITBOX_TOOLTIP_ICONPATH = "Iconpfad. Schreibe hier den Pfad rein, wenn er nicht automatisch gefunden wird oder in der Liste zu finden ist."

	MPOWA_CHECKBUTTON_SORTED = "Sortiere nach Zeit"
	MPOWA_CHECKBUTTON_SORTED_TOOLTIP = "Sortiert die Auren nach Zeit verbleibend (Aufsteigend)."

	MPOWA_SLIDER_DYNAMICORIENTATION = "Ausrichtung: "
	MPOWA_SLIDER_DYNAMICORIENTATION_TOOLTIP = "Wähle die Wachstumsrichtung."

	MPOWA_CHECKBUTTON_DYCNTER = "Keine Zentrierung"
	MPOWA_CHECKBUTTON_DYCNTER_TOOLTIP = "Lasse die Gruppe nicht automatisch ihrerer Mitte zu wachsen und schrumpfen."

	MPOWA_SLIDER_FONT = "Scriftart: "
	MPOWA_SLIDER_FONT_TOOLTIP = "Verschiebe das, um die Schriftart zu ändern."

	MPOWA_SLIDER_SPACING = "Abstand: "
	MPOWA_SLIDER_SPACING_TOOLTIP = "Verschiebe, um den Abstand zwischen den Auren zu verändern."
end
