if (GetLocale() == "deDE") then
	MPOWA_MAINFRAME_HEAD = "Modified Power Auras"
	MPOWA_VERSION = "v0.8"

	MPOWA_BUTTON_EDIT = "Aura bearbeiten"
	MPOWA_BUTTON_ADD = "Aura hinzufügen"
	MPOWA_BUTTON_REMOVE = "Aure entfernen"
	MPOWA_BUTTON_PROFILE = "Profile"
	MPOWA_BUTTON_CLOSE = "Schließen"
	MPOWA_BUTTON_TEST = "Test"
	MPOWA_BUTTON_TESTALL = "Alles testen"
	MPOWA_BUTTON_IMPORT = "Importieren"
	MPOWA_BUTTON_SAVE = "Speichern"
	MPOWA_BUTTON_REMOVE = "Entfernen"
	MPOWA_BUTTON_CANCEL = "Abbrechen"
	MPOWA_BUTTON_OKAY = "Okay"

	MPOWA_CONFIGFRAME_NAME = "Configurations-Frame"
	MPOWA_CONFIGFRAME_EFFECT_EDITOR = "Effekt"
	MPOWA_CONFIGFRAME_TIMER_EDITOR = "Timer"
	MPOWA_CONFIGFRAME_SOUND_EDITOR = "Ton"
	MPOWA_CONFIGFRAME_ABOUT = "Über MPOWA"
	MPOWA_PROFILEFRAME_NAME = "Profil-Editor"
	MPOWA_ICONFRAME_NAME = "Icon-Frame"

	MPOWA_SLIDER_OPACITY = "Deckkraft:"
	MPOWA_SLIDER_OPACITY_TOOLTIP = "Bewege das, um die Deckkraft zu ändern."
	MPOWA_SLIDER_POSX = "Position X:"
	MPOWA_SLIDER_POSX_TOOLTIP = "Bewege das, um die horizontale Position zu ändern."
	MPOWA_SLIDER_POSY = "Position Y:"
	MPOWA_SLIDER_POSY_TOOLTIP = "Bewege das, um die vertikale Position zu ändern."
	MPOWA_SLIDER_SIZE = "Skalierung:"
	MPOWA_SLIDER_SIZE_TOOLTIP = "Bewege das, um die Größe zu ändern."
	MPOWA_SLIDER_BEGINSOUND = "Tondatei: "
	MPOWA_SLIDER_BEGINSOUND_TOOLTIP = "Bewege das, um den Ton zu ändern, wenn eine Aura hinzugefügt wird."
	MPOWA_SLIDER_ENDSOUND = "Tondatei: "
	MPOWA_SLIDER_ENDSOUND_TOOLTIP = "Bewege das, um den Ton zu ändern, wenn eine Aura verschwindet."

	MPOWA_EDITBOX_TOOLTIP = "Schreibe hier den Auranamen hinein, womit das Icon aufgerufen wird."
	MPOWA_EDITBOX_NAME = "Name der Aura:"
	MPOWA_EDITBOX_STACKS_NAME = "Aufladungen:"
	MPOWA_EDITBOX_STACKS_TOOLTIP = "Schreibe hier die Anzahl der Aufladungen rein, um die Aura aufzurufen oder verschwinden zu lassen. Folgende Operatoren sind zulässig: '<5' '>3' '=11' '!5' '>=0' '<=6' '2-8'"
	MPOWA_EDITBOX_DEBUFFDURATION = "Dauer:"
	MPOWA_EDITBOX_DEBUFFDURATION_TOOLTIP = "Schreibe hier die Dauer der Aura des Ziels hinein."
	MPOWA_EDITBOX_FLASHANIM = "Start:"
	MPOWA_EDITBOX_FLASHANIM_TOOLTIP = "Schreibe hier die Dauer rein, wenn es anfangen soll zu blinken."

	MPOWA_CHECKBUTTON_DEBUFF = "Ist Debuff"
	MPOWA_CHECKBUTTON_DEBUFF_TOOLTIP = "Kreuze das an, wenn die Aura ein Debuff ist."
	MPOWA_CHECKBUTTON_SHOWIFNOTACTIVE = "Invertieren"
	MPOWA_CHECKBUTTON_SHOWIFNOTACTIVE_TOOLTIP = "Kreuze das an, um das erscheinen der Aura zu invertieren. Es wird also gezeigt, wenn es NICHT aktiv ist."
	MPOWA_CHECKBUTTON_TIMER = "Timer"
	MPOWA_CHECKBUTTON_TIMER_TOOLTIP = "Kreuze das an, um den Timer zu aktivieren."
	MPOWA_CHECKBUTTON_SHOWCOOLDOWN = "Zeige Cooldown"
	MPOWA_CHECKBUTTON_SHOWCOOLDOWN_TOOLTIP = "Kreuze das an, um die Aura zu zeigen, wenn die Fähigkeit auf cooldown ist."
	MPOWA_CHECKBUTTON_ENEMYTARGET = "|cFFFF8080Gegnerisches Ziel|r"
	MPOWA_CHECKBUTTON_ENEMYTARGET_TOOLTIP = "Kreuze das an, um das gegnerische Ziel zu nutzen, anstatt dir. Notiz: Der Timer wird damit ungenau."
	MPOWA_CHECKBUTTON_INCOMBAT = "Im Kampf"
	MPOWA_CHECKBUTTON_INCOMBAT_TOOLTIP = "Kreuze das an, um einzustellen, wann die Aura gezeigt wird. Nichts => Ignoriere Kampfstatus, Angekreuzt => Zeige es, wenn du im Kampf bist, Kreuz => Zeige es, wenn du NICHT im Kampf bist."
	MPOWA_CHECKBUTTON_INPARTY = "In Gruppe"
	MPOWA_CHECKBUTTON_INPARTY_TOOLTIP = "Kreuze das an, um einzustellen, wann die Aura gezeigt wird. Nichts => Ignoriere Gruppenstatus, Angekreuzt => Zeige es, wenn du in einer Gruppe bist, Kreuz => Zeige es, wenn du NICHT in einer Gruppe bist."
	MPOWA_CHECKBUTTON_INRAID = "Im Schlachtzug"
	MPOWA_CHECKBUTTON_INRAID_TOOLTIP = "Kreuze das an, um einzustellen, wann die Aura gezeigt wird. Nichts => Ignoriere Schlachtzugstatus, Angekreuzt => Zeige es, wenn du im Schlachtzug bist, Kreuz => Zeige es, wenn du NICHT im Schlachtzug bist."
	MPOWA_CHECKBUTTON_ALIVE = "Ist am leben"
	MPOWA_CHECKBUTTON_ALIVE_TOOLTIP = "Kreuze das an, um einzustellen, wann die Aura gezeigt wird. Nichts => Ignoriere status, Angekreuzt => Zeige es, wenn du lebst, Kreuz => Zeige es, wenn du NICHT lebst."
	MPOWA_CHECKBUTTON_MOUNTED = "Ist aufgesattelt"
	MPOWA_CHECKBUTTON_MOUNTED_TOOLTIP = "Kreuze das an, um einzustellen, wann die Aura gezeigt wird. Nichts => Ignoriere status, Angekreuzt => Zeige es, wenn du aufgesattelt bist, Kreuz => Zeige es, wenn du NICHT aufgesattelt bist."
	MPOWA_CHECKBUTTON_FRIENDLYTARGET = "|cFF66CD00Freundliches Ziel|r"
	MPOWA_CHECKBUTTON_FRIENDLYTARGET_TOOLTIP = "Kreuze das an, um das freundliche Ziel zu nutzen, anstatt dir. Notiz: Der Timer wird damit ungenau."
	MPOWA_CHECKBUTTON_ISBATTLEGROUND = "Im Schlachtfeld"
	MPOWA_CHECKBUTTON_ISBATTLEGROUND_TOOLTIP = "Kreuze das an, um einzustellen, wann die Aura gezeigt wird. Nichts => Ignoriere status, Angekreuzt => Zeige es, wenn du im Schlachtfeld bist, Kreuz => Zeige es, wenn du NICHT im Schlachtfeld bist."
	MPOWA_CHECKBUTTON_HUNDREDS = "Zeige hundertstel"
	MPOWA_CHECKBUTTON_HUNDREDS_TOOLTIP = "Kreuze das an, um hundertstel anzeigen zu lassen."
	MPOWA_CHECKBUTTON_COLOR = "Eigene Farbe: "
	MPOWA_CHECKBUTTON_COLOR_TOOLTIP = "Kreuze das an, um deine eigene Farbe zu nutzen, anstatt weiß."
	MPOWA_CHECKBUTTON_BEGINSOUND = "Spiele Ton, wenn eine Aura erscheint"
	MPOWA_CHECKBUTTON_BEGINSOUND_TOOLTIP = "Kreuze das an, um einen Ton abzuspielen, wenn eine Aura erscheint."
	MPOWA_CHECKBUTTON_ENDSOUND = "Spiele Ton, wenn eine Aura verschwindet"
	MPOWA_CHECKBUTTON_ENDSOUND_TOOLTIP = "Kreuze das an, um einen Ton abzuspielen, wenn eine Aura verschwindet."
	MPOWA_CHECKBUTTON_RAIDMEMBER = "|cFF66CD00Schlachtzug/Gruppenmitglied|r"
	MPOWA_CHECKBUTTON_RAIDMEMBER_TOOLTIP = "Kreuze das an, um einen Schlachtzugs- oder Gruppenmitglied zu suchen. Wenn du diese Option nutzt, füge einen Namen hinzu. Zum Beispiel: (Shino)Segen der Freiheit"
	MPOWA_CHECKBUTTON_EXACTNAME = "Genauer Name"
	MPOWA_CHECKBUTTON_EXACTNAME_TOOLTIP = "Nutze den exakten Namen anstatt einen groben filter."
	MPOWA_CHECKBUTTON_FLASHANIM = "Flash Animation"
	MPOWA_CHECKBUTTON_FLASHANIM_TOOLTIP = "Kreuze das an, um die Blinkanimation zu aktivieren."

	MPOWA_SCRIPT_MOUNT_100 = "Erhöht das Bewegungstempo um 100"
	MPOWA_SCRIPT_MOUNT_60 = "Erhöht das Bewegungstempo um 60"

	MPOWA_TEXT_ABOUT_MPOWA = "Modified Power Auras ist die erweiterte Version von Power Auras. Es verfügt über eine vielzahl von Funktionen, die erst mit späteren Versionen hinzukomen. Zusätzlich verfügt es über eigene Funktion, die das AddOn einmalig machen."
	MPOWA_TEXT_CREATOR_TITLE = "Wer hat Modified Power Auras erstellt?"
	MPOWA_TEXT_CREATOR = "VCB wurde von Shino (Albea) <Synced> entwickelt, der auf Kronos (Twinstar.cz) gearbeitet hat. In der Twinstar-Community ist er als Geigerkind bekannt."
	MPOWA_TEXT_SPECIALTHANKS_TITLE = "Speziellen dank an "
	MPOWA_TEXT_SPECIALTHANKS = "Sinesther - Es ist seine AddOn Idee, bloß wurde es nun für Vanilla stark verbessert."
	MPOWA_TEXT_SUPPORTING_TITLE = "Danke für das unterstützen!"
	MPOWA_TEXT_SUPPORTING = "Noch keiner"
end
