MPOWA_MAINFRAME_HEAD = "Modified Power Auras"
MPOWA_VERSION = "v0.1"

MPOWA_BUTTON_EDIT = "Edit Aura"
MPOWA_BUTTON_ADD = "Add Aura"
MPOWA_BUTTON_REMOVE = "Remove Aura"
MPOWA_BUTTON_PROFILE = "Profiles"
MPOWA_BUTTON_CLOSE = "Close"
MPOWA_BUTTON_TEST = "Test"
MPOWA_BUTTON_TESTALL = "Test all"

MPOWA_CONFIGFRAME_NAME = "Configuration frame"
MPOWA_CONFIGFRAME_EFFECT_EDITOR = "Effect Editor"
MPOWA_CONFIGFRAME_TIMER_EDITOR = "Timer Editor"

MPOWA_SLIDER_OPACITY = "Opacity:"
MPOWA_SLIDER_OPACITY_TOOLTIP = "Move this to change the icon opacity."
MPOWA_SLIDER_POSX = "Position X:"
MPOWA_SLIDER_POSX_TOOLTIP = "Move this to change the horizontal position."
MPOWA_SLIDER_POSY = "Position Y:"
MPOWA_SLIDER_POSY_TOOLTIP = "Move this to change the vertical position."
MPOWA_SLIDER_SIZE = "Size:"
MPOWA_SLIDER_SIZE_TOOLTIP = "Move this to change the size."

MPOWA_EDITBOX_TOOLTIP = "Enter here the buff name to trigger the event. The name must be written correctly."
MPOWA_EDITBOX_NAME = "Name of the Buff:"

MPOWA_CHECKBUTTON_DEBUFF = "Debuff"
MPOWA_CHECKBUTTON_DEBUFF_TOOLTIP = "Check this if the aura is a debuff."
MPOWA_CHECKBUTTON_SHOWIFNOTACTIVE = "Show if not active"
MPOWA_CHECKBUTTON_SHOWIFNOTACTIVE_TOOLTIP = "Check this if the icon should be visible if the aura is NOT active."
MPOWA_CHECKBUTTON_TIMER = "Timer"
MPOWA_CHECKBUTTON_TIMER_TOOLTIP = "Check this to enable the timer."
MPOWA_CHECKBUTTON_SHOWCOOLDOWN = "Show cooldown"
MPOWA_CHECKBUTTON_SHOWCOOLDOWN_TOOLTIP = "Check this to show the icon if the ability is on cooldown."